//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.23 at 11:25:22 AM MEZ 
//


package org.relaxng.ns.structure._1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for open-name-classes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="open-name-classes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://relaxng.org/ns/structure/1.0}other"/>
 *         &lt;group ref="{http://relaxng.org/ns/structure/1.0}name-class"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "open-name-classes", propOrder = {
    "anyOrAnyOrName"
})
@XmlSeeAlso({
    OpenNameClasses.Choice.class
})
public class OpenNameClasses {

    @XmlElementRefs({
        @XmlElementRef(name = "choice", namespace = "http://relaxng.org/ns/structure/1.0", type = JAXBElement.class),
        @XmlElementRef(name = "name", namespace = "http://relaxng.org/ns/structure/1.0", type = Name.class),
        @XmlElementRef(name = "nsName", namespace = "http://relaxng.org/ns/structure/1.0", type = NsName.class),
        @XmlElementRef(name = "anyName", namespace = "http://relaxng.org/ns/structure/1.0", type = AnyName.class)
    })
    @XmlAnyElement
    protected List<Object> anyOrAnyOrName;

    /**
     * Gets the value of the anyOrAnyOrName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anyOrAnyOrName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnyOrAnyOrName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link JAXBElement }{@code <}{@link OpenNameClasses.Choice }{@code >}
     * {@link Name }
     * {@link NsName }
     * {@link AnyName }
     * 
     * 
     */
    public List<Object> getAnyOrAnyOrName() {
        if (anyOrAnyOrName == null) {
            anyOrAnyOrName = new ArrayList<Object>();
        }
        return this.anyOrAnyOrName;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://relaxng.org/ns/structure/1.0}open-name-classes">
     *       &lt;attGroup ref="{http://relaxng.org/ns/structure/1.0}common-atts"/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Choice
        extends OpenNameClasses
    {

        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String ns;
        @XmlAttribute
        @XmlSchemaType(name = "anyURI")
        protected String datatypeLibrary;

        /**
         * Gets the value of the ns property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNs() {
            return ns;
        }

        /**
         * Sets the value of the ns property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNs(String value) {
            this.ns = value;
        }

        /**
         * Gets the value of the datatypeLibrary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatypeLibrary() {
            return datatypeLibrary;
        }

        /**
         * Sets the value of the datatypeLibrary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatypeLibrary(String value) {
            this.datatypeLibrary = value;
        }

    }

}
