//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.23 at 11:25:22 AM MEZ 
//


package org.relaxng.structure;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for grammar-content complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="grammar-content">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://relaxng.org/ns/structure/1.0}other"/>
 *         &lt;choice>
 *           &lt;element ref="{http://relaxng.org/ns/structure/1.0}start"/>
 *           &lt;element ref="{http://relaxng.org/ns/structure/1.0}define"/>
 *           &lt;element name="div">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;extension base="{http://relaxng.org/ns/structure/1.0}grammar-content">
 *                   &lt;attGroup ref="{http://relaxng.org/ns/structure/1.0}common-atts"/>
 *                 &lt;/extension>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{http://relaxng.org/ns/structure/1.0}include"/>
 *         &lt;/choice>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grammar-content", propOrder = {
    "anyOrAnyOrStart"
})
@XmlSeeAlso({
    GrammarContent.Div.class,
    Grammar.class
})
public class GrammarContent {

    @XmlElementRefs({
        @XmlElementRef(name = "start", namespace = "http://relaxng.org/ns/structure/1.0", type = Start.class),
        @XmlElementRef(name = "include", namespace = "http://relaxng.org/ns/structure/1.0", type = Include.class),
        @XmlElementRef(name = "div", namespace = "http://relaxng.org/ns/structure/1.0", type = JAXBElement.class),
        @XmlElementRef(name = "define", namespace = "http://relaxng.org/ns/structure/1.0", type = Define.class)
    })
    @XmlAnyElement
    protected List<Object> anyOrAnyOrStart;

    /**
     * Gets the value of the anyOrAnyOrStart property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anyOrAnyOrStart property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnyOrAnyOrStart().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link GrammarContent.Div }{@code >}
     * {@link Define }
     * {@link Element }
     * {@link Start }
     * {@link Include }
     * 
     * 
     */
    public List<Object> getAnyOrAnyOrStart() {
        if (anyOrAnyOrStart == null) {
            anyOrAnyOrStart = new ArrayList<Object>();
        }
        return this.anyOrAnyOrStart;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://relaxng.org/ns/structure/1.0}grammar-content">
     *       &lt;attGroup ref="{http://relaxng.org/ns/structure/1.0}common-atts"/>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Div
        extends GrammarContent
    {

        @XmlAttribute
        @XmlSchemaType(name = "anySimpleType")
        protected String ns;
        @XmlAttribute
        @XmlSchemaType(name = "anyURI")
        protected String datatypeLibrary;

        /**
         * Gets the value of the ns property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNs() {
            return ns;
        }

        /**
         * Sets the value of the ns property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNs(String value) {
            this.ns = value;
        }

        /**
         * Gets the value of the datatypeLibrary property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatatypeLibrary() {
            return datatypeLibrary;
        }

        /**
         * Sets the value of the datatypeLibrary property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatatypeLibrary(String value) {
            this.datatypeLibrary = value;
        }

    }

}
