//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.23 at 11:25:22 AM MEZ 
//


package org.relaxng.structure;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.relaxng.ns.structure._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Data_QNAME = new QName("http://relaxng.org/ns/structure/1.0", "data");
    private final static QName _OpenPatternChoice_QNAME = new QName("http://relaxng.org/ns/structure/1.0", "choice");
    private final static QName _IncludeContentDiv_QNAME = new QName("http://relaxng.org/ns/structure/1.0", "div");
    private final static QName _ExceptNameClassExcept_QNAME = new QName("http://relaxng.org/ns/structure/1.0", "except");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.relaxng.ns.structure._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link Interleave }
     * 
     */
    public Interleave createInterleave() {
        return new Interleave();
    }

    /**
     * Create an instance of {@link AnyName }
     * 
     */
    public AnyName createAnyName() {
        return new AnyName();
    }

    /**
     * Create an instance of {@link OpenNameClasses.Choice }
     * 
     */
    public OpenNameClasses.Choice createOpenNameClassesChoice() {
        return new OpenNameClasses.Choice();
    }

    /**
     * Create an instance of {@link Optional }
     * 
     */
    public Optional createOptional() {
        return new Optional();
    }

    /**
     * Create an instance of {@link Empty }
     * 
     */
    public Empty createEmpty() {
        return new Empty();
    }

    /**
     * Create an instance of {@link ParentRef }
     * 
     */
    public ParentRef createParentRef() {
        return new ParentRef();
    }

    /**
     * Create an instance of {@link OpenNameClasses }
     * 
     */
    public OpenNameClasses createOpenNameClasses() {
        return new OpenNameClasses();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link IncludeContent }
     * 
     */
    public IncludeContent createIncludeContent() {
        return new IncludeContent();
    }

    /**
     * Create an instance of {@link Include }
     * 
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link IncludeContent.Div }
     * 
     */
    public IncludeContent.Div createIncludeContentDiv() {
        return new IncludeContent.Div();
    }

    /**
     * Create an instance of {@link ZeroOrMore }
     * 
     */
    public ZeroOrMore createZeroOrMore() {
        return new ZeroOrMore();
    }

    /**
     * Create an instance of {@link GrammarContent }
     * 
     */
    public GrammarContent createGrammarContent() {
        return new GrammarContent();
    }

    /**
     * Create an instance of {@link OpenPattern }
     * 
     */
    public OpenPattern createOpenPattern() {
        return new OpenPattern();
    }

    /**
     * Create an instance of {@link OneOrMore }
     * 
     */
    public OneOrMore createOneOrMore() {
        return new OneOrMore();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link Mixed }
     * 
     */
    public Mixed createMixed() {
        return new Mixed();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link NsName }
     * 
     */
    public NsName createNsName() {
        return new NsName();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Data.Except }
     * 
     */
    public Data.Except createDataExcept() {
        return new Data.Except();
    }

    /**
     * Create an instance of {@link NotAllowed }
     * 
     */
    public NotAllowed createNotAllowed() {
        return new NotAllowed();
    }

    /**
     * Create an instance of {@link Value }
     * 
     */
    public Value createValue() {
        return new Value();
    }

    /**
     * Create an instance of {@link Grammar }
     * 
     */
    public Grammar createGrammar() {
        return new Grammar();
    }

    /**
     * Create an instance of {@link Start }
     * 
     */
    public Start createStart() {
        return new Start();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Interleave.Choice }
     * 
     */
    public Interleave.Choice createInterleaveChoice() {
        return new Interleave.Choice();
    }

    /**
     * Create an instance of {@link ExceptNameClass }
     * 
     */
    public ExceptNameClass createExceptNameClass() {
        return new ExceptNameClass();
    }

    /**
     * Create an instance of {@link GrammarContent.Div }
     * 
     */
    public GrammarContent.Div createGrammarContentDiv() {
        return new GrammarContent.Div();
    }

    /**
     * Create an instance of {@link Define }
     * 
     */
    public Define createDefine() {
        return new Define();
    }

    /**
     * Create an instance of {@link ExternalRef }
     * 
     */
    public ExternalRef createExternalRef() {
        return new ExternalRef();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Data }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "data")
    public JAXBElement<Data> createData(Data value) {
        return new JAXBElement<Data>(_Data_QNAME, Data.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = OpenPattern.class)
    public JAXBElement<Interleave.Choice> createOpenPatternChoice(Interleave.Choice value) {
        return new JAXBElement<Interleave.Choice>(_OpenPatternChoice_QNAME, Interleave.Choice.class, OpenPattern.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = OneOrMore.class)
    public JAXBElement<Interleave.Choice> createOneOrMoreChoice(Interleave.Choice value) {
        return new JAXBElement<Interleave.Choice>(_OpenPatternChoice_QNAME, Interleave.Choice.class, OneOrMore.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = Mixed.class)
    public JAXBElement<Interleave.Choice> createMixedChoice(Interleave.Choice value) {
        return new JAXBElement<Interleave.Choice>(_OpenPatternChoice_QNAME, Interleave.Choice.class, Mixed.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = List.class)
    public JAXBElement<Interleave.Choice> createListChoice(Interleave.Choice value) {
        return new JAXBElement<Interleave.Choice>(_OpenPatternChoice_QNAME, Interleave.Choice.class, List.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = Interleave.class)
    public JAXBElement<Interleave.Choice> createInterleaveChoice(Interleave.Choice value) {
        return new JAXBElement<Interleave.Choice>(_OpenPatternChoice_QNAME, Interleave.Choice.class, Interleave.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = Optional.class)
    public JAXBElement<Interleave.Choice> createOptionalChoice(Interleave.Choice value) {
        return new JAXBElement<Interleave.Choice>(_OpenPatternChoice_QNAME, Interleave.Choice.class, Optional.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = Data.Except.class)
    public JAXBElement<Interleave.Choice> createDataExceptChoice(Interleave.Choice value) {
        return new JAXBElement<Interleave.Choice>(_OpenPatternChoice_QNAME, Interleave.Choice.class, Data.Except.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenNameClasses.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = OpenNameClasses.class)
    public JAXBElement<OpenNameClasses.Choice> createOpenNameClassesChoice(OpenNameClasses.Choice value) {
        return new JAXBElement<OpenNameClasses.Choice>(_OpenPatternChoice_QNAME, OpenNameClasses.Choice.class, OpenNameClasses.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IncludeContent.Div }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "div", scope = IncludeContent.class)
    public JAXBElement<IncludeContent.Div> createIncludeContentDiv(IncludeContent.Div value) {
        return new JAXBElement<IncludeContent.Div>(_IncludeContentDiv_QNAME, IncludeContent.Div.class, IncludeContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = Interleave.Choice.class)
    public JAXBElement<Interleave.Choice> createInterleaveChoiceChoice(Interleave.Choice value) {
        return new JAXBElement<Interleave.Choice>(_OpenPatternChoice_QNAME, Interleave.Choice.class, Interleave.Choice.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = Group.class)
    public JAXBElement<Interleave.Choice> createGroupChoice(Interleave.Choice value) {
        return new JAXBElement<Interleave.Choice>(_OpenPatternChoice_QNAME, Interleave.Choice.class, Group.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = ZeroOrMore.class)
    public JAXBElement<Interleave.Choice> createZeroOrMoreChoice(Interleave.Choice value) {
        return new JAXBElement<Interleave.Choice>(_OpenPatternChoice_QNAME, Interleave.Choice.class, ZeroOrMore.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenNameClasses }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "except", scope = ExceptNameClass.class)
    public JAXBElement<OpenNameClasses> createExceptNameClassExcept(OpenNameClasses value) {
        return new JAXBElement<OpenNameClasses>(_ExceptNameClassExcept_QNAME, OpenNameClasses.class, ExceptNameClass.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "choice", scope = Define.class)
    public JAXBElement<Interleave.Choice> createDefineChoice(Interleave.Choice value) {
        return new JAXBElement<Interleave.Choice>(_OpenPatternChoice_QNAME, Interleave.Choice.class, Define.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Data.Except }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "except", scope = Data.class)
    public JAXBElement<Data.Except> createDataExcept(Data.Except value) {
        return new JAXBElement<Data.Except>(_ExceptNameClassExcept_QNAME, Data.Except.class, Data.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GrammarContent.Div }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://relaxng.org/ns/structure/1.0", name = "div", scope = GrammarContent.class)
    public JAXBElement<GrammarContent.Div> createGrammarContentDiv(GrammarContent.Div value) {
        return new JAXBElement<GrammarContent.Div>(_IncludeContentDiv_QNAME, GrammarContent.Div.class, GrammarContent.class, value);
    }

}
