//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.23 at 11:25:22 AM MEZ 
//


package org.relaxng.structure;

import java.util.ArrayList;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for open-pattern complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="open-pattern">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{http://relaxng.org/ns/structure/1.0}other"/>
 *         &lt;group ref="{http://relaxng.org/ns/structure/1.0}pattern"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "open-pattern", propOrder = {
    "anyOrAnyOrGroup"
})
@XmlSeeAlso({
    Start.class
})
public class OpenPattern {

    @XmlElementRefs({
        @XmlElementRef(name = "choice", namespace = "http://relaxng.org/ns/structure/1.0", type = JAXBElement.class),
        @XmlElementRef(name = "oneOrMore", namespace = "http://relaxng.org/ns/structure/1.0", type = OneOrMore.class),
        @XmlElementRef(name = "text", namespace = "http://relaxng.org/ns/structure/1.0", type = Text.class),
        @XmlElementRef(name = "mixed", namespace = "http://relaxng.org/ns/structure/1.0", type = Mixed.class),
        @XmlElementRef(name = "list", namespace = "http://relaxng.org/ns/structure/1.0", type = org.relaxng.structure.List.class),
        @XmlElementRef(name = "interleave", namespace = "http://relaxng.org/ns/structure/1.0", type = Interleave.class),
        @XmlElementRef(name = "optional", namespace = "http://relaxng.org/ns/structure/1.0", type = Optional.class),
        @XmlElementRef(name = "empty", namespace = "http://relaxng.org/ns/structure/1.0", type = Empty.class),
        @XmlElementRef(name = "parentRef", namespace = "http://relaxng.org/ns/structure/1.0", type = ParentRef.class),
        @XmlElementRef(name = "notAllowed", namespace = "http://relaxng.org/ns/structure/1.0", type = NotAllowed.class),
        @XmlElementRef(name = "value", namespace = "http://relaxng.org/ns/structure/1.0", type = Value.class),
        @XmlElementRef(name = "grammar", namespace = "http://relaxng.org/ns/structure/1.0", type = Grammar.class),
        @XmlElementRef(name = "ref", namespace = "http://relaxng.org/ns/structure/1.0", type = Ref.class),
        @XmlElementRef(name = "data", namespace = "http://relaxng.org/ns/structure/1.0", type = JAXBElement.class),
        @XmlElementRef(name = "group", namespace = "http://relaxng.org/ns/structure/1.0", type = Group.class),
        @XmlElementRef(name = "zeroOrMore", namespace = "http://relaxng.org/ns/structure/1.0", type = ZeroOrMore.class),
        @XmlElementRef(name = "externalRef", namespace = "http://relaxng.org/ns/structure/1.0", type = ExternalRef.class)
    })
    @XmlAnyElement
    protected java.util.List<Object> anyOrAnyOrGroup;

    /**
     * Gets the value of the anyOrAnyOrGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the anyOrAnyOrGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnyOrAnyOrGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Interleave.Choice }{@code >}
     * {@link OneOrMore }
     * {@link Mixed }
     * {@link Text }
     * {@link org.relaxng.structure.List }
     * {@link Element }
     * {@link Interleave }
     * {@link Optional }
     * {@link Empty }
     * {@link Value }
     * {@link NotAllowed }
     * {@link ParentRef }
     * {@link Ref }
     * {@link Grammar }
     * {@link Group }
     * {@link JAXBElement }{@code <}{@link Data }{@code >}
     * {@link ZeroOrMore }
     * {@link ExternalRef }
     * 
     * 
     */
    public java.util.List<Object> getAnyOrAnyOrGroup() {
        if (anyOrAnyOrGroup == null) {
            anyOrAnyOrGroup = new ArrayList<Object>();
        }
        return this.anyOrAnyOrGroup;
    }

}
