#!/usr/bin/ruby 
require 'rubygems'
require File.dirname($0) + '/../lib/ruby/riddl'
require 'optparse'
require 'pp'

verbose = false
ARGV.options { |opt|
  opt.summary_indent = ' ' * 2
  opt.banner = "Usage:\n#{opt.summary_indent}#{File.basename($0)} [options] [FILENAME]\n"
  opt.on("Options:")
  opt.on("--help", "-h", "This text") { puts opt; exit }
  opt.on("--verbose", "-v", "Write ouput to console") { verbose = true }
  opt.on("Filename is either a description or a declaration.")
  opt.parse!
}
$stderr.close unless verbose
if ARGV.length == 0 || !File.exists?(ARGV[0])
  puts ARGV.options
  exit
end
fname = ARGV[0]

riddl = Riddl::open(fname)

unless riddl.declaration?
  puts 'Not a RIDDL declaration.'
  exit
end
unless riddl.validate!
  puts "Does not conform to specification#{verbose ? '' : ', use -v for details'}."
  exit
end
puts "RIDDL declaration looks valid."

def get_path(d,routes,first=false)
    else  
      routes[m.name.name].each do |k,v|
        v << m.attributes['out'] if v.last == m.attributes['in']  
      end
    end  
  end
  false
end

riddl.find("/dec:declaration/dec:interface").each do |ifa|
  routes = {}
  ifa.find("des:description|dec:filter/des:description").each_with_index
  description.find("des:resource/des:*[@in and @out and not(@in='*')]").each do |m|
    routes[m.name.name] ||= {}
    routes[m.name.name][m.attributes['in']] ||= get_path(m.attributes['out'],ifa.find(')
  end unless description.nil?
  pp routes
end

#1 in "a" out "b": in "a" out "b"   -> suchen b nächste stufe
#2 pass "a":       in "a" out "a"   -> suchen a nächste stufe
#3 in "*" out "a": in "*" out "a"
#4 remove "a":     in "*" out "*-a" -> nächste stufe alle die durch 1,2,3 nicht tangiert wurde
#5 add "a":        in "*" out "*+a" -> nächste stufe alle die durch 1,2,3 nicht tangiert wurde
#6 pass "*"        in "*" out "*"

# mehr als ein add/remove nicht erlaubt
# wenn add/remove kein pass erlaubt
