#!/usr/bin/ruby 
require 'rubygems'
require ::File.dirname(__FILE__) + "/../lib/ruby/file"
require 'optparse'

verbose = false
ARGV.options { |opt|
  opt.summary_indent = ' ' * 2
  opt.banner = "Usage:\n#{opt.summary_indent}#{File.basename($0)} [options] [FILENAME]\n"
  opt.on("Options:")
  opt.on("--help", "-h", "This text") { puts opt; exit }
  opt.on("--verbose", "-v", "Write ouput to console") { verbose = true }
  opt.on("Filename is either a description or a declaration.")
  opt.parse!
}
$stderr.close unless verbose
if ARGV.length == 0 || !File.exists?(ARGV[0])
  puts ARGV.options
  exit
end
fname = ARGV[0]

riddl = Riddl::File::open(fname)

if riddl.description?
  puts 'RIDDL description found.'
elsif riddl.declaration?
  puts 'RIDDL declaration found.'
else  
  puts 'Neither a RIDDL description, nor a RIDDL declaration.'
  exit
end

unless riddl.validate!
  puts "Does not conform to specification#{verbose ? '' : ', use -v for details'}."
  exit
end

if riddl.description?
  messages = riddl.valid_resources?
  if messages.empty?
    puts "RIDDL description looks valid."
  else  
    puts messages.join("\n")
    puts "RIDDL description not valid."
  end
elsif riddl.declaration?
  puts "RIDDL declaration looks valid."
end
